In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

for Logistic Regression & Naive Bayes only

In [30]:
# قراءة الملف
df = pd.read_csv("../datasets/heart_disease_cleaned.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,77.0,1,4,125.0,304.0,0,2,162.0,1,0.0,1,3,3,1
1,76.0,0,3,140.0,197.0,0,1,116.0,0,1.1,2,0,3,0
2,74.0,0,2,120.0,269.0,0,2,121.0,1,0.2,1,1,3,0
3,71.0,0,2,160.0,302.0,0,0,162.0,0,0.4,1,2,3,0
4,71.0,0,3,110.0,265.0,1,2,130.0,0,0.0,1,1,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,35.0,1,4,120.0,198.0,0,0,130.0,1,1.6,2,0,7,1
293,35.0,1,4,126.0,282.0,0,2,156.0,1,0.0,1,0,7,1
294,34.0,1,1,118.0,182.0,0,2,174.0,0,0.0,1,0,3,0
295,34.0,0,2,118.0,210.0,0,0,192.0,0,0.7,1,0,3,0
296,29.0,1,2,130.0,204.0,0,2,202.0,0,0.0,1,0,3,0

In [31]:
X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [32]:
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
273,41.0,1,2,120.0,157.0,0,0,182.0,0,0.0,1,0,3
259,43.0,1,4,115.0,303.0,0,0,181.0,0,1.2,2,0,3
30,66.0,1,4,112.0,212.0,0,2,132.0,1,0.1,1,1,3
22,67.0,0,4,106.0,223.0,0,0,142.0,0,0.3,1,2,3
277,41.0,1,4,110.0,172.0,0,2,158.0,0,0.0,1,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,52.0,1,4,112.0,230.0,0,0,160.0,0,0.0,1,1,3
71,61.0,1,4,140.0,207.0,0,2,138.0,1,1.9,1,1,7
106,58.0,1,4,150.0,270.0,0,2,111.0,1,0.8,1,0,7
270,41.0,0,3,112.0,268.0,0,2,172.0,1,0.0,1,0,3
102,59.0,1,1,178.0,270.0,0,2,145.0,0,4.2,3,0,7

In [35]:
# 3. الأعمدة الفئوية
categorical_columns = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal']

# 4. OneHotEncoding
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

X_train_encoded = encoder.fit_transform(X_train[categorical_columns])
X_test_encoded = encoder.transform(X_test[categorical_columns])

# تحويل النتيجة إلى DataFrame
X_train_encoded_df = pd.DataFrame(X_train_encoded, columns=encoder.get_feature_names_out(categorical_columns))
X_test_encoded_df = pd.DataFrame(X_test_encoded, columns=encoder.get_feature_names_out(categorical_columns))

# إعادة ضبط الفهارس
X_train_encoded_df.index = X_train.index
X_test_encoded_df.index = X_test.index

# حذف الأعمدة الفئوية الأصلية وإضافة المشفرة
X_train_final = pd.concat([X_train.drop(columns=categorical_columns), X_train_encoded_df], axis=1)
X_test_final = pd.concat([X_test.drop(columns=categorical_columns), X_test_encoded_df], axis=1)

# دمج البيانات النهائية
X_train_final = pd.concat([X_train_final, X_train_encoded_df], axis=1)
X_test_final = pd.concat([X_test_final, X_test_encoded_df], axis=1)

اهداف:

X_train_scaled, X_test_scaled: بيانات جاهزة للتدريب على النموذج.

y_train, y_test: الهدف (الـ Labels) بدون أي تغيير.

Normalization or measurement after division in order to prevent information leakage (Data Leakage)

In [ ]:
# تطبيق Standard Scaling على التدريب فقط
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_final)  # نحسب المتوسط والانحراف المعياري من التدريب فقط
X_test_scaled = scaler.transform(X_test_final)        # نطبق نفس القيم على الاختبار

# إذا كنت بتستخدم pandas DataFrame بدل numpy array بعد التقييس:
#  لأجل جلب أسماء الأعمدة وحفظها
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

اهداف الكود:

فصل الميزات والهدف.

تقسيم البيانات بدون تسرب.

تقييس (scaling) بدون استخدام بيانات الاختبار أثناء التدريب.

مهم جدًا لو بتستخدم خوارزميات مثل KNN، SVM، أو الانحدار الخطي.